version: '3.4'

services:
  servicestatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  categoryservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

